#!/usr/bin/env bash
# This script displays listening TCP, UDP, and UNIX sockets, along with their associated PID and program name.

echo "Active Internet connections (only servers)"
ss -ltunp

echo

echo "Active UNIX domain sockets (only servers)"
ss -lxp
