#!/usr/bin/env bash
# script that configure an Ubuntu server

grep -v "localhost" /etc/hosts | grep -v "facebook.com" > /tmp/hosts
echo "127.0.0.2 localhost" >> /tmp/hosts
echo "8.8.8.8 facebook.com" >> /tmp/hosts
cat /tmp/hosts > /etc/hosts